### ISSUE TITLE
RealScience Refactor master issue

### ISSUE THREAD

**Issue by jwvanderbeck** [jwvanderbeck/RealScience#5]
RealScience needs a serious refactor as outlined in https://github.com/jwvanderbeck/RealScience/wiki/Refactor-Design
- [ ] Add Scenario module to act as common data store
- [ ] Rewrite state machine
- [ ] Add instrument PartModule core
- [ ] Create instrument GUI
- [ ] New class to handle the Research Unit as a concrete item
- [ ] Interface between Experiment and Instruments
